MODEL:
  NUM_CLASSES: 3
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", )
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 1200
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 3
  LR: 1e-3

OUTPUT_DIR: 'outputs/resnet_ssd512_voc0712'