MODEL:
  NUM_CLASSES: 4
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", )
  TEST: ("voc_2007_test", )
SOLVER:
  # MAX_ITER: 120000
  MAX_ITER: 44988
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 16
  LR: 1e-3

OUTPUT_DIR: 'outputs/vgg_ssd300_voc0712'